testMatrix = new Matrix(3,3);
testMatrix.randomize();
testMatrix.print();
testMatrix = Matrix.transpose(testMatrix);
testMatrix.print();
console.table(testMatrix.toArray());
testMatrix = Matrix.fromArray([34,23,45,54,67]);
testMatrix.print();
testMatrix = Matrix.map(testMatrix, Matrix.testFunc1);
testMatrix.print();
testMatrix.map(Matrix.testFunc1);
testMatrix.print();
testMatrix = Matrix.subtract(testMatrix, testMatrix);
testMatrix.print();
testMatrix.add(1);
testMatrix.print();
testMatrix.add(testMatrix);
testMatrix.print();
testMatrix.multiply(6);
testMatrix.print();
testMatrix.multiply(testMatrix);
testMatrix.print();
testMatrix = Matrix.fromArray([[2,5],[6,7],[1,8]]);
testMatrix.print();
testMatrix = Matrix.transpose(testMatrix);
testMatrix.print();
testMatrixA = Matrix.fromArray([[1,2,1],[0,1,0],[2,3,4]]);
testMatrixB = Matrix.fromArray([[2,5],[6,7],[1,8]]);
testMatrixA.print();
testMatrixB.print();
testMatrix = Matrix.multiply(testMatrixA, testMatrixB);
testMatrix.print();
